AllCops:
  Exclude:
    - '**/schema.rb'
  TargetRubyVersion: 2.2

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 17

Metrics/MethodLength:
  Max: 21
