default: &default
  adapter: mysql2
  username: root
  host: localhost
  encoding: utf8
  reconnect: true
  pool: 30

development:
  <<: *default
  database: distribusion_challenge_development

test:
  <<: *default
  database: distribusion_challenge_test

production:
  <<: *default
  database: distribusion_challenge
